### ISSUE TITLE
Transaction.find will throw a KeyError on invalid transactions.

### ISSUE THREAD

**Issue by slyngshede** [coolshop-com/AltaPay#32]
Given an invalid transaction id, the Transaction.find() method will throw a KeyError. This is due to an attempt to access a Transactions list not present if the transaction is not found.

`Traceback (most recent call last):
  File "/opt/projects/coolpay2/coolpay/captures/tests.py", line 178, in test_altapay_fail
    event = terminal.capture(event)
  File "/opt/projects/coolpay2/coolpay/terminals/mixins/altapay.py", line 124, in capture
    api=api)
  File "/opt/projects/virtualenv/coolpay2/lib/python3.5/site-packages/altapay/transaction.py", line 22, in find
    if isinstance(response['Body']['Transactions']['Transaction'], list):
KeyError: 'Transactions'`

**Comment by HenrikOssipoff** [comment]
This will result in an `altapay.exceptions.ResourceNotFoundError` in 1.0.dev4
